### ISSUE TITLE
Canvas won't load after update 1.0.45

### ISSUE THREAD

**Issue by KevinRichard-GM** [ironmonk88/monks-little-details#152]
Canvas won't draw after updating to 1.0.45. Shows a Canvas drawing error and something about the Token layer.

foundry.js:319 
        
       Error: Invalid scope for flag data.enabled
[Detected 5 packages: monks-little-details, lib-wrapper, perfect-vision, system:pf2e, catch-up]
    at NPCPF2e.getFlag (document.mjs:575:42)
    at TokenPF2e.tokenRefresh (bloodsplats.js:86:119)
    at TokenPF2e.tokenRefresh (monks-little-details.js:215:42)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at TokenPF2e.🎁Token.prototype.refresh#perfect-vision (tokens.js:5:9)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at TokenPF2e.🎁Token.prototype.refresh#0 (libWrapper-wrapper.js:189:20)
    at TokenPF2e.draw (foundry.js:37903:10)
    at async TokenPF2e.draw (main.bundle.js:1:451768)
    at async Promise.all (index 0)
    at async TokenLayerPF2e.draw (foundry.js:22216:5)
    at async Canvas.draw (foundry.js:20066:11)
    at async Canvas.🎁Canvas.prototype.draw#perfect-vision (canvas.js:405:9)
    at async ScenePF2e.view (foundry.js:17809:7)
    at async Game.initializeCanvas (foundry.js:5679:20)
    at async Game.setupGame (main.js:84:2)
    at async Game._initializeGameView (foundry.js:6510:5)
    at async Game.initialize (foundry.js:5433:5)

**Comment by ironmonk88** [comment]
Sorry about that.
1.0.46 should fix that.

**Comment by ironmonk88** [comment]
This should be fixed in the latest version.
