### ISSUE TITLE
[BUG] In DnD5e 3.0.x "Clear all" button throws an error when actor is "Unconscious"

### ISSUE THREAD

**Issue by strongpauly** [ironmonk88/monks-little-details#288]
Clicking on the "Clear all" button in the Status Effects popout in the token hud does not clear any Status Effects.  An error can be seen in the console.

**Steps to reproduce the behavior**
1. Select a token
2. Right click on token to show token hud
3. Click on status effect icon
4. Apply "Unconscious"
5. Click on "Clear all" button

**Expected behavior**
"Unconscious" and related status effects should be cleared

**Actual behaviour**
Effect is not cleared, and error is shown in console:
```
commons.js:3894 Uncaught (in promise) Error: undefined. ActiveEffect5e [dnd5eincapacitat] validation errors:
  name: may not be undefined
[Detected 2 packages: system:dnd5e, monks-little-details]
    at DataModelValidationFailure.asError (commons.js:3894:14)
    at ActiveEffect5e.validate (commons.js:7164:61)
    at new DataModel (commons.js:6918:12)
    at new Document (commons.js:7583:3)
    at new BaseActiveEffect (commons.js:8914:3)
    at new ClientDocumentMixin (foundry.js:13979:7)
    at new ActiveEffect (foundry.js:17730:1)
    at new ActiveEffect5e (active-effect.mjs:8:16)
    at ActiveEffect5e.fromStatusEffect (active-effect.mjs:62:12)
    at TokenDocument5e.toggleActiveEffect (token.mjs:108:32)
    at Token5e.toggleEffect (foundry.js:55799:44)
    at TokenHUD.clearAll (hud-changes.js:153:35)
    at HTMLDivElement.i (jquery.min.js:2:89049)
    at HTMLDivElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

 - Browser: Mac OS Electron
 - Foundry Version v11 315
 - System : D&D5e 3.0.1
 - Module version: 11.07
 - Are there any errors in the console: Yes (see above)
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction: No

**Comment by strongpauly** [comment]
Might be related to the fact that there are multiple copies of some Status Effects:

<img width="918" alt="Screenshot 2024-02-10 at 14 13 56" src="https://github.com/ironmonk88/monks-little-details/assets/853954/f6a2734e-42b6-45fe-942c-b4bb472bca5a">

**Comment by strongpauly** [comment]
Similar error to #284

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
Wasn't related.  5e just broke some things.
