### ISSUE TITLE
[BUG] Incompatibilities with DAE

### ISSUE THREAD

**Issue by Kregoras** [ironmonk88/monks-little-details#318]
**Describe the bug**
When installed with newest DAE version for DnD5e 4.1+ when an effect is assigned like disengage via token menu, when the effect is disabled Foundry get's frozen.

**To Reproduce**
1. Install both modules, monks-little-details and DAE (with dependencies)
2. Create a new character 
3. Place character on table
4. Select token
5. Apply the effect Disengage via menu
6. Remove the effect via token menu
7. Browser is frozen (a browser reload is required, foundry keeps working) and the effect is not removed.

**Expected behavior**
Remove the effect and do not freeze the browser

**Screenshots**
![Captura de pantalla 2024-12-16 204007](https://github.com/user-attachments/assets/718dd77e-0305-44d9-ae1e-ee363d24e6a0)
![Captura de pantalla 2024-12-16 204135](https://github.com/user-attachments/assets/abe8561c-54cb-40c8-81e5-d302a125f613)

**Please complete as much of the following information as possible:**
 - Browser [Chrome, Edge and inbuilt Foundry browser]
 - Foundry Version [e.g. v12]
 - System [DnD5e 4.1.2]
 - Module version: DAE 12.0.6.2, Monk's lil details 12.04, socketlib 1.1.0 and libwrapper 1.13.2.0
 - Are there any errors in the console: Apparently not
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. I narrowed it to both modules stated.

**Additional context**

**Comment by davidhawbecker** [comment]
Can confirm this bug. Same thing happening here and I'm on v12 and 5e. 3.3.1.

**Comment by ChrisRosser** [comment]
I also have the issue!

For me there are two concentrating effects. One works correctly. The other throws this error on being applied:

```
Error: The async option for Roll#evaluate has been removed. Use Roll#evaluateSync for synchronous roll evaluation.
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at Roll.evaluate (foundry-esm.js:63561:23)
    at enrichDamage (enrichers.mjs:382:51)
    at enrichString (enrichers.mjs:55:27)
    at _replaceTextContent.replaceParent.replaceParent (foundry.js:69632:61)
    at TextEditor._replaceTextContent (foundry.js:69752:26)
    at async TextEditor.enrichHTML (foundry.js:69530:25)
    at async #k (action-handler.js:1571:46)
    at async #w (action-handler.js:1201:17)
    at async action-handler.js:1146:67
    at async Promise.all (index 3)
    at async ActionHandler.buildActions (action-handler.js:1146:19)
    at async ActionHandler.buildActivations (action-handler.js:308:56)
    at async #d (action-handler.js:812:26)
    at async Promise.all (index 3)
    at async #i (action-handler.js:152:9)
    at async ActionHandler.buildSystemActions (action-handler.js:129:21)
    at async #h (action-handler.js:208:72)
    at async Promise.all (index 0)
    at async ActionHandler.buildHud (action-handler.js:98:31)
    at async #It (token-action-hud.js:1157:14)
    at async TokenActionHud.update (token-action-hud.js:1093:20)
```

And locks the browser up on being removed with this repeating error message:

```
DEBUG | Automated Animations | No Animation matched for Item {token: Token5e, targets: Array(0), item: ActiveEffect5e, activeEffect: true}
constants.js:3
```

**Comment by Celldweller** [comment]
I can confirm this bug. 

Browser [Chrome 132.0.6834.160]
Foundry Version [12.331]
System [DnD5e 3.3.1]
Module version: DAE 11.3.68, Monk's Little Details 12.04, socketlib 1.1.0 and libwrapper 1.13.2.0

It happens with all extra statuses.

**Comment by papodadorpg** [comment]
Same here! But mine is not on the browser but in Foundry.

Foundry 12.331
D&D 5e 331

DAE 11.3.68 
Little Details 12.04
Socketlib 1.0.13
Libwrapper 1.13.2.0

**Comment by efromhere** [comment]
I have found that unchecking 
```
DAE -> dependent conditions
```
will allow you to use the monks extra statuses without the program stalling when deactivating those statuses (raging, exhaustion, hasted, turned, etc.)

from what I can tell, DAE seems to have changed something in the way these statuses are handled some time after version 11.3.58 as this issue doesn't seem to be present in 
```
DAE 11.3.58 
Monks Little Details 12.04 
Foundry 12.331  
D&D 5e 3.3.1
```

but is present when using 
```
DAE 11.3.68 
Monks Little Details 12.04 
Foundry 12.331  
D&D 5e 3.3.1
```

Hope that helps
